# Open source: the what and why 

'Open Source' software is software covered by a license that legally allows access and inspection of the software's source code. The many varieties of open-source licenses determine what you can then do with the software's source code, i.e.  copy, modify, contribute or redistribute. Being able to view and then do something with source code wasn't always so. The term 'open source' has been in use at least since the 1990's [@Peterson2018] and the principles behind the term pre-date computer software. Thus, as long as there has been source code there have been efforts to make it 'open source'. 

As computing systems became widely adopted in universities and beyond, the value of freely accessing the IT's source code became apparent. This effort was described as making software 'free' by Richard Stallman and formalised by the creation of the Free Software Foundation in 1985, including the creation of a legally enforceable licenses (the GNU Public License) to enshrine source code as 'free', that is, having the freedom to access. Although this effort was the genesis of today's open-source communities, many people mistakenly understood 'free' to mean gratis, which was incorrect: most open-source licenses allow the software to be sold for a fee [@OSI]. As is the case, even if the main goal of open source is not creating software gratis, it so happens that the majority of open-source software is made available at no cost.  Regardless of whether it is sold for a fee or not, the term 'open source' is the preferred term by most with respect to software with a license that allows access to the source code.

Readers coming from the pharmaceutical industry probably perceive a contradiction here: how can software which is typically gratis to use, have any intrinsic value to either business or private users? Fair enough: this industry depends on capital investment which then depends on retaining the details of their drugs and production secret. The difference lies in the utility of (some) software, versus, in this example, a drug or therapy. Certain categories of software enable the creation of new value. Obvious examples being programming languages enabling creation of specialized applications which can support a specific business process, e.g. C, Python, R and many others. The ability to use and improve these open source languages freely accelerate in multiple dimensions the ability to create business value, e.g. specialized smart phone apps that offers a service to end-users. Imagine if you have an idea for a smart phone app, but before you can write a line of code, you need to buy a license to install that language. And after investing the time and money to access this language you realise it doesn't work as well as you need for your particular app. Or worse yet, it has a bug which renders it unfit for your purpose. Little chance you can resolve this quickly. Open-source software does not have these restrictions so you can focus all your resources on end-user value, not the tools needed for creation. 

Open-sourcing software solutions is also a mindset approach. As you use available open-source code, you are using bits and pieces to create a piece of software/analytics that is greater than the individual parts. By open-sourcing your solution, you give others the opportunity to build ontop of your work, as well as improve your work itself by contributing. Ultimately, this comes back around to yourself: What you have available at your disposal is now greater, than if you worked in a silo.

Open Source is also a step towards ensuring repoducibility. Consider an analysis done in a propriety language by a pharmaceutical company. An academic accessing the same data through a data sharing initiative may find results that contradict those done using the propriety tool. Such a researcher would not be able reproduce the results nor investigate the source of the discrepancy---and in fact any attempt to reproduce results is dependent on the for-profit company providing a license to generate that insight [@Rodrigues2022]. 

The drugs and therapies manufactured by the pharmaceutical industry are the equivalent of a smart phone app: they provide end-user value. It’s sound business logic to open source the tools used to create these products: remove the restrictions to creating drugs and enable each company to sharpen their focus on developing and delivering them. 